databases:
  - name: alertify_bend
    plan: free
    databaseName: alertify_bend
    user: postgres

services:
  - type: web
    plan: free
    name: alertify
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn alertify].asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alertify_bend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4