# Generated by Django 5.0.1 on 2024-02-21 14:10

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                default=25405651500, max_length=13, unique=True
            ),
            preserve_default=False,
        ),
    ]
